//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class bills_with_apartments
    {
        public int bill_id { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<decimal> total { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public Nullable<int> house_number { get; set; }
        public Nullable<int> room_number { get; set; }
    }
}
