//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab4
{
    using System;
    using System.Collections.Generic;
    
    public partial class apartments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public apartments()
        {
            this.rents = new HashSet<rents>();
        }
    
        public int apartment_id { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public Nullable<int> house_number { get; set; }
        public Nullable<int> room_number { get; set; }
        public Nullable<decimal> day_cost { get; set; }
        public System.Data.Entity.Spatial.DbGeography location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rents> rents { get; set; }
    }
}
