//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rentEntities : DbContext
    {
        public rentEntities()
            : base("name=rentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartments> apartments { get; set; }
        public virtual DbSet<bill_details> bill_details { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<rents> rents { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
